# Generated by Django 4.2 on 2023-05-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvupload', models.FileField(upload_to='uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
