# Generated by Django 4.2 on 2023-05-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_csv_delete_quesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
